### ISSUE TITLE
Swap first and last li element jquery

### ISSUE THREAD

**Issue by quyen91** [quyen91/ishare#16]
+ Using rotate for `li + ul`
```css
ul {
    transform: rotate(180deg);
}
ul > li {
    transform: rotate(-180deg);
}
```
https://stackoverflow.com/a/25695025/3551956
