### ISSUE TITLE
Strim long string with css by max-width and overflow-hidden

### ISSUE THREAD

**Issue by quyen91** [quyen91/ishare#7]
```css
{
    max-width: 150px;
    overflow: hidden;
    white-space: nowrap;
    -o-text-overflow: ellipsis;
    text-overflow: ellipsis; // dau ...
}

```
